#ifndef CLASSDEFS_H
#define CLASSDEFS_H

#define ACT_HUMAN 0
#define ACT_ROBOT 1
#define ACT_MAX 2

#define OBJ_BREAD_RATION 0
#define OBJ_BOTTLE_WATER 1
#define OBJ_DAGGER 2
#define OBJ_PLUMED_CAP 3
#define OBJ_GOLD_COIN 4
#define OBJ_MAX 5

#define FEAT_CLOSED_WOODEN_DOOR 0
#define FEAT_OPEN_WOODEN_DOOR 1
#define FEAT_TREE 2
#define FEAT_MAX 3

#define TILE_FLOOR 0
#define TILE_GRASS 1
#define TILE_WALL 2
#define TILE_WATER 3
#define TILE_MAX 4

#define COND_CURSED 0
#define COND_MAX 1

#define ACTION_WALK_BASIC 0
#define ACTION_TAKE_BASIC 1
#define ACTION_DROP_BASIC 2
#define ACTION_EQUIP_BASIC 3
#define ACTION_UNEQUIP_BASIC 4
#define ACTION_EAT_BASIC 5
#define ACTION_DRINK_BASIC 6
#define ACTION_OPEN_BASIC 7
#define ACTION_CLOSE_BASIC 8
#define ACTION_STRIKE 9
#define ACTION_PUNCH 10
#define ACTION_POINT 11
#define ACTION_LINE 12
#define ACTION_MAX 13

#endif
